name: Deploy to GitHub Pages (Reusable)

on:
  workflow_call:

jobs:
  call:
    runs-on: ubuntu-latest

    steps:
      - name: Call OCI Endpoint
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          HOOK_URL: ${{ secrets.HOOK_URL }}
        run: |
          curl -X POST "$HOOK_URL" \
            -H "Authorization: Bearer $API_TOKEN" \

